-- Hardening incremental e idempotente do Portal Cerro Cora.
-- Antes de executar: gere um backup do banco e confira o ambiente selecionado.
-- Este arquivo nao apaga conteudo, usuarios ou objetos do Storage.

begin;

-- O reset de tentativas so e necessario depois que o login criou uma sessao.
revoke execute on function public.clear_login_rate_limit(text) from anon;
grant execute on function public.clear_login_rate_limit(text) to authenticated;

-- Garante que scripts legados nao deixem mutacoes do bucket abertas a qualquer login.
drop policy if exists "Authenticated insert tourism files" on storage.objects;
drop policy if exists "Authenticated update tourism files" on storage.objects;
drop policy if exists "Authenticated delete tourism files" on storage.objects;

create policy "Authenticated insert tourism files"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'tourism' and public.is_admin(auth.uid()));

create policy "Authenticated update tourism files"
  on storage.objects for update to authenticated
  using (bucket_id = 'tourism' and public.is_admin(auth.uid()))
  with check (bucket_id = 'tourism' and public.is_admin(auth.uid()));

create policy "Authenticated delete tourism files"
  on storage.objects for delete to authenticated
  using (bucket_id = 'tourism' and public.is_admin(auth.uid()));

-- Analytics so pode ser gravado pela rota server-side com service role.
alter table if exists public.analytics_events enable row level security;
drop policy if exists "analytics_events public insert" on public.analytics_events;
revoke insert, update on public.analytics_events from anon, authenticated;

alter table if exists public.analytics_events
  add column if not exists dedupe_key text;

create unique index if not exists analytics_events_dedupe_key_idx
  on public.analytics_events(dedupe_key)
  where dedupe_key is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'analytics_events_type_allowed'
  ) then
    alter table public.analytics_events
      add constraint analytics_events_type_allowed check (
        event_type in (
          'card_view', 'page_view', 'whatsapp_click', 'map_click',
          'instagram_click', 'site_click', 'phone_click', 'reserve_click',
          'details_click', 'gallery_click', 'carousel_click', 'cta_click'
        )
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'analytics_events_entity_type_allowed'
  ) then
    alter table public.analytics_events
      add constraint analytics_events_entity_type_allowed check (
        entity_type in ('restaurant', 'lodging', 'city_service')
      ) not valid;
  end if;
end $$;

create table if not exists public.analytics_rate_limits (
  identifier text primary key,
  event_count integer not null default 0,
  reset_at timestamptz not null,
  updated_at timestamptz not null default now()
);

alter table public.analytics_rate_limits enable row level security;
revoke all on public.analytics_rate_limits from anon, authenticated;

create or replace function public.consume_analytics_rate_limit(
  p_identifier text,
  p_max_events integer default 120,
  p_window_seconds integer default 60
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_count integer;
begin
  if p_identifier is null or length(p_identifier) < 8 then
    return false;
  end if;

  delete from public.analytics_rate_limits
  where reset_at < now() - interval '1 hour';

  insert into public.analytics_rate_limits(identifier, event_count, reset_at, updated_at)
  values (
    left(p_identifier, 160),
    1,
    now() + make_interval(secs => greatest(10, least(p_window_seconds, 3600))),
    now()
  )
  on conflict (identifier) do update set
    event_count = case
      when public.analytics_rate_limits.reset_at <= now() then 1
      else public.analytics_rate_limits.event_count + 1
    end,
    reset_at = case
      when public.analytics_rate_limits.reset_at <= now()
        then now() + make_interval(secs => greatest(10, least(p_window_seconds, 3600)))
      else public.analytics_rate_limits.reset_at
    end,
    updated_at = now()
  returning event_count into current_count;

  return current_count <= greatest(1, least(p_max_events, 1000));
end;
$$;

revoke all on function public.consume_analytics_rate_limit(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_analytics_rate_limit(text, integer, integer)
  to service_role;

-- Log administrativo imutavel, sem copiar payloads completos ou segredos.
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid,
  action text not null,
  entity_type text not null,
  entity_id text,
  result text not null default 'success',
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;
revoke insert, update, delete on public.admin_audit_log from anon, authenticated;
grant select on public.admin_audit_log to authenticated;

drop policy if exists "admin_audit_log admin read" on public.admin_audit_log;
create policy "admin_audit_log admin read"
  on public.admin_audit_log for select to authenticated
  using (public.is_admin(auth.uid()));

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log(created_at desc);
create index if not exists admin_audit_log_entity_idx
  on public.admin_audit_log(entity_type, entity_id, created_at desc);

create or replace function public.capture_admin_audit_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data jsonb;
begin
  if auth.uid() is null or not public.is_admin(auth.uid()) then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  insert into public.admin_audit_log(
    admin_user_id, action, entity_type, entity_id, summary
  ) values (
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    row_data ->> 'id',
    jsonb_build_object(
      'active', coalesce(row_data -> 'ativo', row_data -> 'is_active'),
      'plan', coalesce(row_data -> 'plan_type', row_data -> 'plano', row_data -> 'plan')
    )
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function public.capture_admin_audit_event() from public, anon, authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'pontos_turisticos', 'pousadas', 'restaurantes', 'city_services',
    'service_categories', 'admin_users'
  ] loop
    if to_regclass('public.' || table_name) is not null then
      execute format('drop trigger if exists admin_audit_%I on public.%I', table_name, table_name);
      execute format(
        'create trigger admin_audit_%I after insert or update or delete on public.%I for each row execute function public.capture_admin_audit_event()',
        table_name,
        table_name
      );
    end if;
  end loop;
end $$;

-- Retencao controlada: executar somente por job server-side autorizado.
create or replace function public.purge_old_analytics_events(p_retention_days integer default 400)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  delete from public.analytics_events
  where created_at < now() - make_interval(days => greatest(30, least(p_retention_days, 1825)));
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.purge_old_analytics_events(integer)
  from public, anon, authenticated;
grant execute on function public.purge_old_analytics_events(integer) to service_role;

commit;

-- Validacao posterior sugerida, apos conferir dados legados:
-- alter table public.analytics_events validate constraint analytics_events_type_allowed;
-- alter table public.analytics_events validate constraint analytics_events_entity_type_allowed;
